#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
# to make executable: chmod u+x AllrunVectorized
cd code
mpic++ -O3 -o project4.x main.cpp lib.cpp isingmodel.cpp -larmadillo -llapack -lblas
#c++  -O3 -o project4.x main.cpp lib.cpp isingmodel.cpp -larmadillo -llapack -lblas
#g++ -o main.exe main.cpp lib.cpp
mpirun -n $1 ./project4.x $2 $3 $4 $5 $6 $7 $8
#cd ../results
#mv ../code/*.txt .




