#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
# to make executable: chmod u+x Allrun

c++  -O3 -o main.x main.cpp -L/usr/local/lib -larmadillo -llapack -lblas  
#g++ -o main.exe main.cpp lib.cpp
./main.x $1 $2 $3 $4 $5 $6 $7 $8 $9 $10
cd results
mv ../*.csv .




